### ISSUE TITLE
Getting zero drops for Colonies Fisher

### ISSUE THREAD

**Issue by Delfayne** [Saereth/inferno_issues#39]
Getting no drops at all for the fisher despite running it for many days.

The drop rates look a little low in the config, 2% base for kelp, the highest at T1.

Interestingly, it also says `- skill` in red, implying this is reduced. Reduced to zero maybe?

![image](https://user-images.githubusercontent.com/97418063/177888478-4ab0eaa0-c9a5-4d01-9eb5-d998e12244bb.png)

To contrast, here's prismarine at T5 showing + skill modifier in green:

![image](https://user-images.githubusercontent.com/97418063/177888552-97b1a061-1e0c-4341-921a-7253aa4f8514.png)

`- skill` kinda makes sense if the goal is to reduce "chaff" drops, but I don't think that's what we want here.

Raise the chance or invert the skill change perhaps. See what feels better.

**Comment by Saereth** [comment]
+skill is because prismarine is treasure class -skill because kelp is "junk" so looting enchant for example (or higher citizen skill) would make prismarine more common and kelp more rare. I increase the drops rates substantially for this stuff though for next update. re-open if this is still an issue.

**Comment by Delfayne** [comment]
Cheers. I figured it was junk vs treasure. But I wasn't getting anything. Strange as King got a few. :thinking:
